{
    "name": "Diseño de reportes Doralex",
    "version": "19.0.3.13.5",
    "category": "Reporting",
    "summary": "V5.3 restaurado: cotización por empresa; rótulo de comprobante",
    "description": "Cada empresa conserva su cotización. El rótulo fiscal de factura es Número de Comprobante Fiscal / Gubernamental / de Régimen Especial. OC / PO no sustituye el comprobante.",
    "author": "Justech",
    "website": "https://doralexgroup.cloud",
    "license": "LGPL-3",
    "depends": [
        "web",
        "sale",
        "purchase",
        "account",
        "stock",
        "l10n_do_accounting",
        "justech_warranty",
        "justech_alexander_base",
        "justech_alexander_admin",
    ],
    "data": [
        "security/ir.model.access.csv",
        "reports/paperformat.xml",
        "reports/headers.xml",
        "reports/layout.xml",
        "reports/components.xml",
        "reports/brand_sync.xml",
        "reports/preview_templates.xml",
        "reports/report_inherits.xml",
        "reports/warranty_report.xml",
        "reports/statement.xml",
        "reports/propet_proforma.xml",
        "data/mail_templates.xml",
        "views/print_buttons.xml",
        "views/sale_print_wizard.xml",
        "views/preview_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.report_assets_common": [
            "justech_alexander_reports/static/src/css/report.css"
        ]
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
