{
    "name": "Doralex UX — menús y catálogo",
    "version": "19.0.1.0.1",
    "category": "Hidden",
    "summary": "Limpia el lanzador y el catálogo: el motor fiscal y la nómina siguen instalados, sin apps técnicas sueltas",
    "description": "Overlay Doralex: mueve DGII y e-CF bajo Contabilidad → Fiscal Dominicana, oculta addons técnicos del catálogo de Aplicaciones y usa nombres visibles en español sin repetir Justech. No desinstala módulos ni cambia nombres técnicos.",
    "author": "Justech",
    "website": "https://doralexgroup.cloud",
    "license": "LGPL-3",
    "depends": [
        "justech_alexander_admin",
        "justech_l10n_do_base",
        "justech_ecf_core",
        "l10n_do_ecf_connector",
        "justech_warranty",
        "justech_fiscal_admin",
        "justech_admin_center",
        "justech_alexander_website",
        "account_accountant",
        "justech_l10n_do_ncf",
        "justech_l10n_do_reports",
    ],
    "data": [
        "views/menus.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
