{
    "name": "Doralex UX — menús y catálogo",
    "version": "19.0.1.1.0",
    "category": "Hidden",
    "summary": "Launcher limpio, Fiscal Dominicana agrupada y e-CF apagado por defecto",
    "description": "Overlay Doralex: menús fiscales agrupados, e-CF/DGII ocultos hasta activar el switch, administración/aprobaciones/auditoría bajo Ajustes. No desinstala módulos ni cambia nombres técnicos.",
    "author": "Justech",
    "website": "https://doralexgroup.cloud",
    "license": "LGPL-3",
    "depends": [
        "justech_alexander_admin",
        "justech_l10n_do_base",
        "justech_ecf_core",
        "l10n_do_ecf_connector",
        "justech_warranty",
        "justech_fiscal_admin",
        "justech_admin_center",
        "justech_alexander_website",
        "account_accountant",
        "justech_l10n_do_ncf",
        "justech_l10n_do_reports",
        "justech_l10n_do_payments_withholding",
        "justech_approval_flow",
        "justech_global_audit_log",
        "purchase",
    ],
    "data": [
        "data/ir_config_parameter.xml",
        "views/menus.xml",
        "views/res_config_settings_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
