{
    "name": "Doralex UX — menús y catálogo",
    "version": "19.0.1.6.4",
    "category": "Hidden",
    "summary": "Launcher limpio, aprobaciones y padrón OFF, retenciones RD 2026",
    "description": "Overlay Doralex: menús fiscales agrupados, e-CF/DGII/padrón/aprobaciones desactivados de forma segura. Catálogo de retenciones Ley 30-26 por selección manual. Histórico de aprobaciones conservado bajo Administración. No desinstala módulos ni cambia nombres técnicos.",
    "author": "Justech",
    "website": "https://doralexgroup.cloud",
    "license": "LGPL-3",
    "depends": [
        "justech_alexander_admin",
        "justech_l10n_do_base",
        "justech_ecf_core",
        "l10n_do_ecf_connector",
        "justech_warranty",
        "justech_fiscal_admin",
        "justech_admin_center",
        "justech_alexander_website",
        "account_accountant",
        "justech_l10n_do_ncf",
        "justech_l10n_do_reports",
        "justech_l10n_do_payments_withholding",
        "justech_approval_flow",
        "justech_global_audit_log",
        "purchase",
        "stock",
        "sale",
        "justech_sale_purchase_trace",
    ],
    "data": [
        "data/ir_config_parameter.xml",
        "security/approval_visibility.xml",
        "views/menus.xml",
        "views/approval_request_views.xml",
        "views/approval_branding.xml",
        "views/res_config_settings_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/withholding_catalog_views.xml",
        "views/login_views.xml",
    ],
    "assets": {
        "web.assets_frontend_minimal": [
            "justech_alexander_ux/static/src/login/show_login_form.js",
        ],
        "web.assets_backend": [
            "justech_alexander_ux/static/src/navbar/navbar.css",
            "justech_alexander_ux/static/src/navbar/navbar.xml",
            "justech_alexander_ux/static/src/navbar/user_companies.js",
        ],
        "web.assets_web": [
            "justech_alexander_ux/static/src/navbar/navbar.css",
            "justech_alexander_ux/static/src/navbar/navbar.xml",
            "justech_alexander_ux/static/src/navbar/user_companies.js",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
