"""Datos legales y bancarios ya entregados en el Levantamiento. No se inventan."""

EXCEL_COMPANIES = [
    {
        "name": "INVERSIONES DORALEX,S.RL.",
        "trade": "Doralex",
        "rnc": "132220112",
        "activity": "SERVICIO, COMERCIO, AGRARIO, INDUSTRIAL",
        "street": "AV. SAN VICENTE DE PAUL, NO. 115, LOS MINA",
        "province": "SANTO DOMINGO",
        "municipality": "SANTO DOMINGO ESTE",
        "phone": "849-207-5817",
        "email": "inversionesdoralex@gmail.com",
        "legal": "Alexander Piña Aquino",
        "legal_id": "223-0157134-9",
        "currency": "DOP",
        "start": "2020-11-02",
    },
    {
        "name": "COMERCIALIZADORA DE ALIMENTOS PIÑARIA, S.R.L.",
        "trade": "Piñaria",
        "rnc": "132271068",
        "activity": "SERVICIO, COMERCIO, DISTRIBUCION, IMPORTACION",
        "street": "CALLE 8 NO. 8, LAS AMERICAS, SANTO DOMINGO ESTE",
        "province": "SANTO DOMINGO",
        "municipality": "SANTO DOMINGO ESTE",
        "phone": "849-207-5817",
        "email": "piñariascomercializadora@gmail.com",
        "legal": "Alba Rafaelina Arias Mora",
        "legal_id": "280-103907-0",
        "currency": "DOP",
        "start": "2021-03-01",
    },
    {
        "name": "DOMINION BUSINESS,S.R.L.",
        "trade": "Dominion",
        "rnc": "132721502",
        "activity": "COMERCIO, SERVICIO",
        "street": "CALLE ESPAILLAT NO. 10, ZONA COLONIAL, DISTRITO NACIONAL",
        "province": "DISTRITO NACIONAL",
        "municipality": "DISTRITO NACIONAL",
        "phone": "829-941-5257",
        "email": "dominionsrl@hotmail.com",
        "legal": "Arisleydi Contreras Suero",
        "legal_id": "402-4200332-1",
        "currency": "DOP",
        "start": "2022-11-09",
    },
    {
        "name": "INVERSIONES EL MAYUMA, S.R.L.",
        "trade": "El Mayuma",
        "rnc": "132710152",
        "activity": "COMERCIO, SERVICIO",
        "street": "CALLE CLUB ACTIVO 20-30, NO.47, RESPALDO ALMA ROSA ll",
        "province": "SANTO DOMINGO",
        "municipality": "SANTO DOMINGO ESTE",
        "phone": "829-696-1881",
        "email": "inversioneselmayuma@gmail.com",
        "legal": "Eldris Marlenny Ramirez Minaya",
        "legal_id": "402-4218015-2",
        "currency": "DOP",
        "start": "2022-09-14",
    },
    {
        "name": "REMPART GROUP S.R.L.",
        "trade": "Rempart",
        "rnc": "132769155",
        "activity": "COMERCIO, SERVICIO",
        "street": "AV. SAN VICENTE DE PAUL, NO. 122, LOS MINA",
        "province": "SANTO DOMINGO",
        "municipality": "SANTO DOMINGO ESTE",
        "phone": "849-394-1927",
        "email": "rempartsrl@hotmail.com",
        "legal": "Agustin Ventura Alcantara",
        "legal_id": "402-2314668-5",
        "currency": "DOP",
        "start": "2023-01-19",
    },
    {
        "name": "BLUE ELITE, S.R.L.",
        "trade": "Blue Elite",
        "rnc": "133371261",
        "activity": "COMERCIO, SERVICIO",
        "street": "AV. SAN VICENTE DE PAUL, NO. 122, LOS MINA",
        "province": "SANTO DOMINGO",
        "municipality": "SANTO DOMINGO ESTE",
        "phone": "809-614-1306",
        "email": "bluelitesrl@hotmail.com",
        "legal": "Geilin Rosario Suero",
        "legal_id": "402-1097505-4",
        "currency": "DOP",
        "start": "2025-04-04",
    },
]

EXCEL_BANKS = [
    {
        "company": "INVERSIONES DORALEX,S.RL.",
        "number": "9604436830",
        "balance": 5000000,
        "balance_date": "05//08/2026",
        "type": "Corriente",
    },
    {
        "company": "COMERCIALIZADORA DE ALIMENTOS PIÑARIA, S.R.L.",
        "number": "9604097492",
        "balance": 2450000,
        "balance_date": "05//08/2026",
        "type": "Corriente",
    },
    {
        "company": "DOMINION BUSINESS,S.R.L.",
        "number": "9605588726",
        "balance": 1500000,
        "balance_date": "05//08/2026",
        "type": "Ahorros",
    },
    {
        "company": "INVERSIONES EL MAYUMA, S.R.L.",
        "number": "9605543104",
        "balance": 3000000,
        "balance_date": "05//08/2026",
        "type": "Corriente",
    },
    {
        "company": "REMPART GROUP S.R.L.",
        "number": "9608739498",
        "balance": 4600000,
        "balance_date": "05//08/2026",
        "type": "Corriente",
    },
    {
        "company": "BLUE ELITE, S.R.L.",
        "number": "9608670542",
        "balance": 1250000,
        "balance_date": "05//08/2026",
        "type": "Corriente",
    },
]

BATCH = "ALEXANDER_OPENING_2026-09-04"
EXPECTED_AR = "27240211.80"
EXPECTED_PDFS = 26
EXPECTED_MISSING_PDF = "B1300000016"
