view = env.ref("justech_approval_flow.view_justech_approval_request_search")
arch = str(view.get_combined_arch())
count = arch.count("Pendientes de mi aprobación")
print("ux", env["ir.module.module"].sudo().search([("name", "=", "justech_alexander_ux")]).latest_version)
print("my_approval_label_count", count)
print("has_my_pending", 'name="my_pending"' in arch)
print("has_my_requests", "Mis solicitudes" in arch)
print("has_flujo", "Flujo de Aprobaciones" in str(env.ref("base.res_config_settings_view_form").get_combined_arch()))
print("posted", env["account.move"].sudo().search_count([("move_type", "=", "out_invoice"), ("state", "=", "posted")]))
