{
    "name": "Doralex Microsoft Mail",
    "version": "19.0.1.0.0",
    "category": "Communications",
    "summary": "Correo Microsoft 365 por empresa vía Graph (shared mailboxes y aliases)",
    "description": "Integra Microsoft Graph con Odoo Community: envío y recepción por company_id, sin SMTP de shared mailbox y sin mezclar dominios entre empresas.",
    "author": "Justech",
    "website": "https://doralexgroup.cloud",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "crm",
        "sale",
        "purchase",
        "account",
        "justech_alexander_base",
        "justech_alexander_admin",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/res_company_views.xml",
        "views/inbox_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
