print("DB", env.cr.dbname)
so = env["sale.order"].sudo().browse(217)
print("SO", so.exists(), so.name, so.amount_tax, so.amount_total)
inv = env["account.move"].sudo().browse(1853)
print("INV16", inv.exists(), inv.name, inv.state, inv.amount_tax, getattr(inv, "justech_do_ncf", None))
pay = env["account.payment"].sudo().browse(573)
print("PAY", pay.exists(), pay.name, pay.amount, pay.state)
print("INV3", [(i.name, i.amount_residual, getattr(i, "justech_do_ncf", None)) for i in env["account.move"].sudo().browse([1854, 1855, 1856])])
print("TAX461 tags", env["account.tax"].sudo().browse(461).invoice_repartition_line_ids.mapped(lambda l: l.tag_ids.mapped("name")))
print("PROD untouched check: not running on doralex_prod")
