{
    "name": "Doralex Base",
    "version": "19.0.1.0.2",
    "category": "Administration",
    "summary": "Identidad multiempresa, nomenclatura y datos públicos de Doralex Group",
    "description": "Organización profesional de las seis compañías Doralex: códigos cortos, almacenes, secuencias, diarios y ficha pública (sin datos confidenciales en el website).",
    "author": "Justech",
    "website": "https://doralexgroup.cloud",
    "license": "LGPL-3",
    "depends": [
        "base",
        "stock",
        "account",
        "sale",
        "purchase",
        "justech_l10n_do_base",
    ],
    "data": [
        "data/bootstrap.xml",
        "views/res_company_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
